CONFIG_FILE		:= mcu_config.h

CFG_MCU_8BIT 	:= "sed -i 's/define MCU_8_BIT       1/define MCU_8_BIT       0/g' "$(ROOT_BASE)/$(CONFIG_FILE)
CFG_MCU_16BIT 	:= "sed -i 's/define MCU_16_BIT      1/define MCU_16_BIT      0/g' "$(ROOT_BASE)/$(CONFIG_FILE)
CFG_MCU_32BIT 	:= "sed -i 's/define MCU_32_BIT      0/define MCU_32_BIT      1/g' "$(ROOT_BASE)/$(CONFIG_FILE)

CFG_TOOLCHAIN_GCC		:= "sed -i 's/define GCC             0/define GCC             1/g' "$(ROOT_BASE)/$(CONFIG_FILE)
CFG_TOOLCHAIN_AVR		:= "sed -i 's/define GCC_AVR         1/define GCC_AVR         0/g' "$(ROOT_BASE)/$(CONFIG_FILE)
CFG_TOOLCHAIN_XTENSA	:= "sed -i 's/define GCC_XTENSA      1/define GCC_XTENSA      0/g' "$(ROOT_BASE)/$(CONFIG_FILE)

config:
	@bash -c $(CFG_MCU_8BIT)
	@bash -c $(CFG_MCU_16BIT)
	@bash -c $(CFG_MCU_32BIT)

	@bash -c $(CFG_TOOLCHAIN_GCC)
	@bash -c $(CFG_TOOLCHAIN_AVR)
	@bash -c $(CFG_TOOLCHAIN_XTENSA)
	
