#======================================================================
# select which tools to use as compiler, 
# librarian and linker
#======================================================================
# 		CFLAGS
# CFLAGS		+= -std=c99 
CFLAGS 		+= -Wall -O1 -Os
CFLAGS		+= -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums
# CFLAGS		+= $(addprefix -I,$(ROOT_BASE))
# CFLAGS		+= $(addprefix -I,$(EDK_BASE))

# CFLAGS
# CXXFLAGS	+= -std=c++11
CXXFLAGS	+= 
# CXXFLAGS	+= $(addprefix -I,$(ROOT_BASE))
# CXXFLAGS	+= $(addprefix -I,$(EDK_BASE))
#======================================================================
# select which tools to use as compiler, librarian and linker
#======================================================================
AR = ar
ARFLAGS = rv
#======================================================================
# select which tools to use as compiler, librarian and linker
# CC
# CXX
CCX_FLAG	:= $(CC)

ifeq ($(CCX_FLAG), $(CXX))
	CCX := $(CXX)
	CCXFLAGS := $(CXXFLAGS)
else
	CCX := $(CC)
	CCXFLAGS := $(CFLAGS)
endif

#======================================================================
all: checkdirs build $(PROGRAMS)

build: checkdirs build-obj

build-obj: $(EDK_DEP) $(EDK_OBJ) 

$(BUILD_BASE)/%.o: $(EDK_BASE)/%.c
	$(CC) $(CCXFLAGS) $(MLD_INC) -c $< -o $@

$(BUILD_BASE)/%.o: $(EDK_BASE)/%.cpp
	$(CXX) $(CCXFLAGS) $(MLD_INC) -c $< -o $@	

$(BUILD_BASE)/%.deps: $(EDK_BASE)/%.c $(EDK_BASE)/%.h
	@$(CC) -MM $< > $@
	@$(CC) $< -MM -MT $@ >> $@

$(BUILD_BASE)/%.deps: $(EDK_BASE)/%.cpp $(EDK_BASE)/%.h
	@$(CXX) -MM $< > $@
	@$(CXX) $< -MM -MT $@ >> $@

checkdirs: $(EDK_BUILD_DIR)
	
$(EDK_BUILD_DIR):
	$(MKDIR) $@
clean:
	$(RMDIR) $(EDK_BUILD_DIR)

